### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by roberbnd** [olyckne/laravel-elixir-karma#4]
Hi
Excuse me, I tried but I don't finish of understand
![screenshot_20160825_200530](https://cloud.githubusercontent.com/assets/4907027/17991883/2f703f84-6b08-11e6-87af-4406d19719e7.png)
![screenshot_20160825_200633](https://cloud.githubusercontent.com/assets/4907027/17991882/2f6e7032-6b08-11e6-885c-82c21070bd15.png)

I have karma.conf.js in the same dir ~/workspace/bakery/karma.conf.js

Do you know why?

**Comment by olyckne** [comment]
You need to run `gulp tdd` or `gulp watch` for karma to run, becase of issue mentioned in https://github.com/olyckne/laravel-elixir-karma/pull/1
